default: &default
  adapter: postgresql
  # schema_search_path: public
  encoding: unicode
  host: localhost
  username: sgh # postgres
  password:
  pool: 5

development:
  <<: *default
  database: bp_development


test:
  <<: *default
  database: bp_test

production:
  <<: *default
  database: bp_production
  username: cc_back
  password: <%= ENV['CC_BACK_DATABASE_PASSWORD'] %>
